### ISSUE TITLE
Update to cloud-provider-openstack version 1.20

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-openstack#148]
**How to categorize this issue?**

/area open-source
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:
The v1.19 release of the [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.19.0) is out, so let's to update it!

/cc @dkistner @kon-angelo @MartinWeindel

**Comment by rfranzke** [comment]
Ping, we have hit a problem which might be resolved by the 1.19 Kubernetes CCM library, ref https://github.com/kubernetes/kubernetes/issues/90512, so we should get the 1.19 OpenStack CCM

**Comment by ialidzhikov** [comment]
The issue is referenced is already fixed in v1.18 with this cherry-pick https://github.com/kubernetes/kubernetes/pull/94253. I am not sure how it is related to cloud-controller-manger.

**Comment by ialidzhikov** [comment]
Can you explain how this is related to the cloud-controller-manager?

**Comment by rfranzke** [comment]
There is https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.20.0 now that we should start using for 1.20 clusters.

**Comment by ialidzhikov** [comment]
The occm@v1.20.0 update is currently blocked by https://github.com/kubernetes/cloud-provider-openstack/issues/1356 as we use custom lb-provider (`f5networks`) and there is regression in occm@v1.20.0 that does not allow setting custom lb-provider.
