### ISSUE TITLE
Infra integration test failing on PR

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener-extension-provider-openstack#180]
**How to categorize this issue?**

/area quality dev-productivity
/kind bug
/priority normal
/platform openstack

**What happened**:

Currently, the infra integration test is failing when executed via the TM bot, because the test run can't reach out the SAP-internal OpenStack installation (isolated environment):
see https://github.com/gardener/gardener-extension-provider-openstack/pull/179#issuecomment-731589791

**What you expected to happen**:
The infrastructure integration test to be executable on a PR via the TM bot.

**How to reproduce it (as minimally and precisely as possible)**:
`/test-single`

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by dguendisch** [comment]
Unfortunately this scenario cannot work right now. We would need to implement https://github.com/gardener/test-infra/issues/314 first.
