### ISSUE TITLE
Add a "--user-agent" CLI parameter to occm/csi components

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener-extension-provider-openstack#214]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:

`--user-agent` parameter adds an additional prefix to a `User-Agent` request header

**Why is this needed**:

If we set `--user-agent %openstack_domain_name% --user-agent %openstack_project_name% --user-agent %gardener_cluster_name%`, the resulting User-Agent header will look like:

```
User-Agent: %domain% %project% %cluster_name% occm/version gophercloud/2.0.0
``` 

This information will help us to quickly identify the suspect through HTTP access logs, when we face an issue.

**Comment by vpnachev** [comment]
This is for the cloud-controller-manager? Or maybe some other components also support it?

**Comment by dkistner** [comment]
As far as I can see the `kube-controller-manager` does not have such a field and I guess this would be the important component to have the user agent information. Maybe csi has similar flags, where we can enable it.

I will check if we can assign the user agent for the `cloud-controller-manager`.

**Comment by dkistner** [comment]
Checked also cinder csi plugin. It supports the `--user-agent` flag, so let's enable the user agents also here.

**Comment by kayrus** [comment]
If I'm not mistaken after 1.19 we don't configure kcm to use provider plugins. Correct me if I'm wrong.
