### ISSUE TITLE
Add an ability to specify a subnet pattern for a router static IP

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener-extension-provider-openstack#219]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:

Here is an example of the pattern, which will allow to create a router on a specific FIP subnet:

```hcl
data "openstack_networking_network_v2" "ext_network" {
  name = "FloatingIP-external"
}

data "openstack_networking_subnet_ids_v2" "ext_subnets" {
  name_regex = "FloatingIP-internet-"
  network_id = data.openstack_networking_network_v2.ext_network.id
}

resource "openstack_networking_router_v2" "router_1" {
  name                = "my_router"
  external_network_id = data.openstack_networking_network_v2.ext_network.id
  external_subnet_ids = data.openstack_networking_subnet_ids_v2.ext_subnets.ids
}
```

This structure will be available once the Terraform OpenStack provider v1.36 is released.

**Why is this needed**:

To control the router creation.

**Comment by dkistner** [comment]
Awesome :) 
/assign
