### ISSUE TITLE
Update openstack terraform provider configuration

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener-extension-provider-openstack#220]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:

Current provider configuration should be adjusted:

https://github.com/gardener/gardener-extension-provider-openstack/blob/91107343d96686ff9e59098d19536c0e2af3985c/charts/internal/openstack-infra/templates/main.tf#L1-L9

Insecure flag must be removed:

```hcl
insecure    = true
```

And a `max_retries` should be set in order support the 429 response code with a `Retry-After` header.

**Why is this needed**:

* Production environment must not contain the `insecure=true` parameter.
* `max_retries` starting from Terrafrom OpenStack provider v1.36 will support the 429 response code and sleep accordingly. This is needed in order to decrease high amount of API calls, when a technical user password was changed and a user gets blocked by identity.

**Comment by dkistner** [comment]
**Status**
- [ ] Add max retries → https://github.com/gardener/gardener-extension-provider-openstack/pull/222
- [ ] Remove `insecure=true` require to have the ability passing a proper CA cert to secure the TLS connections

**Comment by kayrus** [comment]
it looks like the corresponding changes are already implemented: https://github.com/gardener/gardener-extension-provider-openstack/blob/31ecded0959a7c5eca8bdbabe877607dcb1797af/pkg/internal/infrastructure/templates/main.tpl.tf#L19-L22
