### ISSUE TITLE
make generate fails with missing executables

### ISSUE THREAD

**Issue by morremeyer** [gardener/gardener-extension-provider-openstack#250]
**How to categorize this issue?**
/area dev-productivity
/kind bug
/priority 5
/platform openstack

**What happened**:

Cloning the repository and running `make generate` returns:

```
❯ make generate
> Generate
Successfully generated controller registration at ../../example/controller-registration.yaml
pkg/apis/config/v1alpha1/doc.go:20: running "gen-crd-api-reference-docs": exec: "gen-crd-api-reference-docs": executable file not found in $PATH
../../../hack/update-codegen.sh: line 21: GOPATH: unbound variable
pkg/apis/openstack/doc.go:18: running "../../../hack/update-codegen.sh": exit status 1
pkg/apis/openstack/v1alpha1/doc.go:20: running "gen-crd-api-reference-docs": exec: "gen-crd-api-reference-docs": executable file not found in $PATH
pkg/imagevector/imagevector.go:15: running "packr2": exec: "packr2": executable file not found in $PATH
pkg/openstack/client/types.go:15: running "mockgen": exec: "mockgen": executable file not found in $PATH
netpol-gen/netpol-gen.go:20:2: cannot find package "github.com/gardener/gardener-extension-provider-openstack/test/e2e/netpol-gen/app" in any of:
	/usr/local/go/src/github.com/gardener/gardener-extension-provider-openstack/test/e2e/netpol-gen/app (from $GOROOT)
	/home/mmeyer/go/src/github.com/gardener/gardener-extension-provider-openstack/test/e2e/netpol-gen/app (from $GOPATH)
netpol-gen/netpol-gen.go:22:2: cannot find package "github.com/gardener/gardener/extensions/test/e2e/framework/networkpolicies/generators" in any of:
	/usr/local/go/src/github.com/gardener/gardener/extensions/test/e2e/framework/networkpolicies/generators (from $GOROOT)
	/home/mmeyer/go/src/github.com/gardener/gardener/extensions/test/e2e/framework/networkpolicies/generators (from $GOPATH)
netpol-gen/netpol-gen.go:23:2: cannot find package "k8s.io/gengo/args" in any of:
	/usr/local/go/src/k8s.io/gengo/args (from $GOROOT)
	/home/mmeyer/go/src/k8s.io/gengo/args (from $GOPATH)
netpol-gen/netpol-gen.go:24:2: cannot find package "k8s.io/klog" in any of:
	/usr/local/go/src/k8s.io/klog (from $GOROOT)
	/home/mmeyer/go/src/k8s.io/klog (from $GOPATH)
test/e2e/doc.go:15: running "go": exit status 1
make: *** [Makefile:127: generate] Error 1
```

This specifically happens when the generation script processes `./test/...` and `./pkg/...`.

**What you expected to happen**:

`make generate` to run sucessfully

**How to reproduce it (as minimally and precisely as possible)**:

1. Clone the repository 
2. Run `make generate`

**Anything else we need to know?**:

I am most likely missing a/some setup step(s), but unfortunately I didn’t see any documentation on that. Researching the error as a go beginner didn’t get me far.

**Comment by ialidzhikov** [comment]
Make sure you have run `make install-requirements` and you have the project cloned under $GOPATH.

Ref https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md#get-the-sources

> > Note: Gardener is using Go modules and cloning the repository into `$GOPATH` is not a hard requirement. However it is still recommended to clone into `$GOPATH` because `k8s.io/code-generator` does not work yet outside of `$GOPATH` - [kubernetes/kubernetes#86753](https://github.com/kubernetes/kubernetes/issues/86753).

**Comment by morremeyer** [comment]
@ialidzhikov Thanks! Then I’ll wait for the code-generator fix, having the repos under GOPATH does not work with my current workflow.
