### ISSUE TITLE
Storageclass gardener.cloud-fast not using cinder.csi.openstack.org 

### ISSUE THREAD

**Issue by dat1041988** [gardener/gardener-extension-provider-openstack#321]
**How to categorize this issue?**

/area TODO
/kind bug
/priority 3
/platform openstack

**What happened**:
Already installed garden cluster with storageclass using cinder.csi.openstack.org provider.
When i create shoot cluster, storageclass gardener.cloud-fast is created with provisioner kubernetes.io/cinder.
Volume cannot create using this storageclass and is in pending state.
**What you expected to happen**:
storageclass gardener.cloud-fast is created with provisioner cinder.csi.openstack.org
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I don't know this is a bug or i miss somethings in configuration.
**Environment**:

- Gardener version (if relevant): 1.25.2
- Extension version: 1.19.1
- Kubernetes version (use `kubectl version`): 1.20.7
- Cloud provider or hardware configuration: Openstack
- Others:

**Comment by vpnachev** [comment]
> is created with provisioner kubernetes.io/cinder.

Yes. And the CSI driver is backward compatible with the in-tree provisioner and this should be working fine.

Could please add a step-by-step guide how to reproduce what you are observing together with events and logs?
/status author-action

**Comment by dat1041988** [comment]
@vpnachev 
Steps:
Install k8s v1.20.7 using kubespray, OS ubuntu 20.04, with options:
cloud_provider: external
external_cloud_provider: openstack
cinder_csi_enabled: true

Install VPA into k8s cluster.
Create default storageclass using cinder.csi.openstack.org.

Deploy garden cluster using garden-setup without any errors.
Check Seed cluster status is ready.
Using GUI to create shoot cluster. Check PVC in shoot namespace, two PVCs created using default storageclass are bound, one PVC (etcd pvc) created using gardener.cloud-fast SC is in pending state.

I edit acre.yaml to config etcd storage using my default storageclass:

landscape:
  gardener:
    extensions:
      provider-openstack:
        valueOverwrites:
          config:
            etcd:
              storage:
                className: cinder
                capacity: 25Gi
                provisioner: cinder.csi.openstack.org

And when i create shoot cluster, i got another issue:

Check required extensions failed (retry failed with context deadline exceeded, last error: extension controllers missing or unready: map[ControlPlane/openstack:{} Infrastructure/openstack:{} Worker/openstack:{}])

Many thanks!

**Comment by dat1041988** [comment]
Using default intree cinder for SC garden.cloud-fast  & CSI migration enable feature-gates.
