### ISSUE TITLE
Each Infrastructure reconciliation recreates security group rules

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-openstack#335]
**How to categorize this issue?**

/area quality
/kind bug
/priority 2
/platform openstack

**What happened**:
Each Infrastructure reconciliation recreates security group rules

**What you expected to happen**:
No changes when reconciliation Infrastructure that was successfully applied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an openstack Shoot

2. Make sure that the initial `terraform apply` succeeds with something similar to:

```
Apply complete! Resources: 11 added, 0 changed, 0 destroyed.
```

3. After successful Shoot creation, reconcile the Infrastructure:

```
$ k -n shoot--foo--bar annotate infra bar gardener.cloud/operation=reconcile
```

4. Make sure that 2 security group rules are recreated:

```
openstack_networking_router_interface_v2.router_nodes: Refreshing state... [id=42f09e56-3dd5-4aab-b425-18e3cf231234]
openstack_networking_secgroup_rule_v2.cluster_udp_all: Destroying... [id=b6a8cb69-d3a0-46f3-b122-dfaf706b1234]
openstack_networking_secgroup_rule_v2.cluster_tcp_all: Destroying... [id=52f61ee3-d05d-47f8-b173-43e6c76b1234]
openstack_networking_secgroup_rule_v2.cluster_tcp_all: Destruction complete after 8s
openstack_networking_secgroup_rule_v2.cluster_tcp_all: Creating...
openstack_networking_secgroup_rule_v2.cluster_udp_all: Still destroying... [id=b6a8cb69-d3a0-46f3-b122-dfaf706b1234, 10s elapsed]
openstack_networking_secgroup_rule_v2.cluster_udp_all: Destruction complete after 14s
openstack_networking_secgroup_rule_v2.cluster_udp_all: Creating...
openstack_networking_secgroup_rule_v2.cluster_tcp_all: Creation complete after 7s [id=82453f5e-462d-41f6-add8-82ab7bf91234]
openstack_networking_secgroup_rule_v2.cluster_udp_all: Creation complete after 2s [id=4dc52ebc-2f05-4a89-bb36-8629c1521234]

Apply complete! Resources: 2 added, 0 changed, 2 destroyed.
```

5. Repeat step 3.

6. Make sure that again 2 security group rules are recreated.

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.20.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by kon-angelo** [comment]
I can confirm that it happens. However I checked the TF config and state before and after and I didn't find any difference (worthy of making TF recreate the secgroup rules). Only the `cluster_tcp_all` and `cluster_udp_all` rules get recreated.

This could be an issue with the terraform provider itself.
