### ISSUE TITLE
K8s Conformance check failing for 1.21

### ISSUE THREAD

**Issue by einfachnuralex** [gardener/gardener-extension-provider-openstack#366]
**How to categorize this issue?**

/area control-plane
/kind bug
/platform openstack

**What happened**:

Running the conformance check on a Shoot with Kubernetes version 1.21, we had the following failed test:

```
[sig-auth] ServiceAccounts should support OIDC discovery of service account issuer
# Error output:
2021/12/10 10:46:15 OK: Got token
2021/12/10 10:46:15 validating with in-cluster discovery
2021/12/10 10:46:15 OK: got issuer https://api.shootname.internal.x.x
2021/12/10 10:46:15 Full, not-validated claims:
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://api.shootname.internal.x.x", Subject:"system:serviceaccount:svcaccounts-3132:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1639133774, NotBefore:1639133174, Iss
2021/12/10 10:46:15 OK: Constructed OIDC provider for issuer https://api.shootname.internal.x.x
2021/12/10 10:46:15 failed to validate with in-cluster discovery: failed to verify signature: fetching keys oidc: get keys failed Get "https://x.x.x.x:443/openid/v1/jwks": x509: certificate is valid for 127.0.0.1, 100.64.0.1, not x.x.x.x
2021/12/10 10:46:15 falling back to validating with external discovery
2021/12/10 10:46:15 OK: got issuer https://api.shootname.internal.x.x
2021/12/10 10:46:15 Full, not-validated claims:
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://api.shootname.internal.x.x", Subject:"system:serviceaccount:svcaccounts-3132:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1639133774, NotBefore:1639133174, Iss
2021/12/10 10:46:15 Get "https://api.shootname.internal.x.x/.well-known/openid-configuration": x509: certificate signed by unknown authority
```

This problem should be solved by Gardener by setting `--external-hostname` to the API Server URL for OIDC config:

https://github.com/gardener/gardener/blob/5867624a45a1cd92e6fd48e1fae5773b67bc8ee5/pkg/operation/botanist/component/kubeapiserver/deployment.go#L453

But the `--external-hostname` is set to the IP address of the API server by the Openstack extension webhook:

https://github.com/gardener/gardener-extension-provider-openstack/blob/719a343a36b133764f8563b6ec1eec25dfe6d6c1/pkg/webhook/controlplaneexposure/ensurer.go#L83

Which leads to the failing test. We fixed it by removing the line 83 in the Openstack extension webhook ensurer, so the Gardener external hostname setting will be used.

Should we remove this line in a PR or is this needed for other functionality?

**What you expected to happen**:

We would expect the API URL of the API Server to be passed as the external hostname.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): 1.36
- Extension version: 1.22
- Kubernetes version (use `kubectl version`): 1.21.5

**Comment by dguendisch** [comment]
Related: https://github.com/gardener/gardener/issues/4023
@dkistner @kon-angelo wondering why this test passes in our openstack setup 🤔

**Comment by ialidzhikov** [comment]
> Related: [gardener/gardener#4023](https://github.com/gardener/gardener/issues/4023) @dkistner @kon-angelo wondering why this test passes in our openstack setup 🤔

Because we run with the ManagedIstio and APIServerSNI feature gates enabled. The mutation in https://github.com/gardener/gardener-extension-provider-openstack/blob/719a343a36b133764f8563b6ec1eec25dfe6d6c1/pkg/webhook/controlplaneexposure/ensurer.go#L83 does not happen when the feature gates are enabled because of the early exit in https://github.com/gardener/gardener-extension-provider-openstack/blob/719a343a36b133764f8563b6ec1eec25dfe6d6c1/pkg/webhook/controlplaneexposure/ensurer.go#L62-L64

(`IsAPIServerExposureManaged` should return true when ManagedIstio and APIServerSNI are enabled).

**Comment by einfachnuralex** [comment]
That's a good point. I forgot to mention that we don't use Istio and SNI :) 

But is the line to overwrite the external hostname then still needed?
