### ISSUE TITLE
Error code not added

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-openstack#606]
**How to categorize this issue?**

/area quality
/area ops-productivity
/kind bug
/platform openstack

**What happened**:
Worker is failing to be deleted with the following error:
```yaml
    lastError:
      description: 'Error deleting Worker: could not instantiate actuator context:
        failed to create openstack client: Authentication failed'
      lastUpdateTime: "2023-04-04T19:14:40Z"
    lastOperation:
      description: 'Error deleting Worker: could not instantiate actuator context:
        failed to create openstack client: Authentication failed'
      lastUpdateTime: "2023-04-04T19:14:40Z"
      progress: 50
      state: Error
      type: Delete
```

This error message should have been categotized as `ERR_INFRA_UNAUTHENTICATED` as it contains the string `Authentication failed` which should be matched in https://github.com/gardener/gardener-extension-provider-openstack/blob/9d13b55441fa56a698aff3712ba71f097ad29778/pkg/apis/openstack/helper/error_codes.go#L24

**What you expected to happen**:
The Worker lastError to have the error code `ERR_INFRA_UNAUTHENTICATED` added.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.32.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
Fixed by https://github.com/gardener/gardener-extension-provider-openstack/pull/619
/close
