### ISSUE TITLE
gardener-extension-provider-openstack PODs are in CrashLoopBackOff

### ISSUE THREAD

**Issue by yinkun111** [gardener/gardener-extension-provider-openstack#878]
**How to categorize this issue?**

/kind bug
/platform openstack

**What happened**:
It is found that gardener-extension-provider-openstack PODs are in CrashLoopBackOff status in Openstack environment

The error is as following:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1dfc5fb]

goroutine 1171 [running]:
github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow.(*FlowContext).ensureConfiguredNetwork(0xc00261c2c0, {0x27fbb58?, 0xc001e70cf0?})
        /go/src/github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/reconcile.go:209 +0xfb
github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow.(*FlowContext).ensureNetwork(0x3b785c0?, {0x27fbc00?, 0xc00031a0e0?})
        /go/src/github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/reconcile.go:196 +0x28
github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/shared.(*BasicFlowContext).AddTask.TaskFn.Timeout.func1({0x27fbb58?, 0xc001e70cf0?})
        /go/pkg/mod/github.com/gardener/gardener@v1.97.1/pkg/utils/flow/taskfn.go:35 +0x59
github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/shared.(*BasicFlowContext).AddTask.(*BasicFlowContext).wrapTaskFn.func2({0x27fbb58, 0xc001e70cf0})
        /go/src/github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/shared/basic_context.go:169 +0x3ba
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2()
        /go/pkg/mod/github.com/gardener/gardener@v1.97.1/pkg/utils/flow/flow.go:226 +0x165
created by github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode in goroutine 714
        /go/pkg/mod/github.com/gardener/gardener@v1.97.1/pkg/utils/flow/flow.go:222 +0x4f0
```

The shoot cluster spawn a new machine and this machine can not get available IP from Openstack neutron network,

In this scenario, when it calls the function

https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/controller/infrastructure/infraflow/reconcile.go#L201-L209

then cause gardener-extension-provider-openstack stuck in "CrashLoopBackOff" status.

please investigate this issue.

please check the the full log at attachment
[Full_log.log](https://github.com/user-attachments/files/17407536/Full_log.log)

**What you expected to happen**:
gardener-extension-provider-openstack works normally

**How to reproduce it (as minimally and precisely as possible)**:
within Openstack setting, if the shoot can not get available IP can cause this issue.

**Anything else we need to know?**:
no

**Environment**:
Openstack

**Comment by kon-angelo** [comment]
Hi @yinkun111, 

> The shoot cluster spawn a new machine and this machine can not get available IP from Openstack neutron network,

The error log here is only relevant for the infrastructure reconciliation. I do not see the connection with spawning a new machine. That being said, we should address the panic.

Can you post the infrastructureConfig of the shoot ? Was the shoot ever succesfully reconciled in the past ?

**Comment by kon-angelo** [comment]
I think @AndreasBurger already identified the issue and will proceed with a fix.
